---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: bridge
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Melbourne
      - UMASK=002
    volumes:
      - /docker/sonarr:/config
      - /media:/media #optional
      - /downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  sonarr4k:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr4k
    network_mode: bridge
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Melbourne
      - UMASK=002
    volumes:
      - /docker/sonarr4k:/config
      - /media:/media #optional
      - /downloads:/downloads #optional
    ports:
      - 8989:8990
    restart: unless-stopped    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: bridge
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Melbourne
      - UMASK=002
    volumes:
      - /docker/radarr:/config
      - /media:/media #optional
      - /downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  radarr4k:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr4k
    network_mode: bridge
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Melbourne
      - UMASK=002
    volumes:
      - /docker/radarr4k:/config
      - /media:/media #optional
      - /downloads:/downloads #optional
    ports:
      - 7878:7879
    restart: unless-stopped    
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    network_mode: bridge
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Melbourne
      - UMASK=002
    volumes:
      - /docker/lidarr:/config
      - /media:/media #optional
      - /downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
  sportarr:
    image: sportarr/sportarr:latest
    container_name: sportarr
    network_mode: bridge
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Melbourne
      - UMASK=002
    volumes:
      - /docker/sportarr:/config
      - /media/Sportsing:/data #optional
      - /downloads:/downloads #optional
    ports:
      - 1867:1867
    restart: unless-stopped
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    network_mode: bridge
    environment:
      - LOG_LEVEL=debug
      - PUID=0
      - PGID=0
      - TZ=Australia/Melbourne
      - UMASK=002
    ports:
      - 5055:5055
    volumes:
      - /docker/seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped    